// classnames' templates
export const classNames = [

  // BEM
  { // main section styles
    docTitle: 'document-title',
    section: 'section-container',
    carousel: 'carousel',
    carouselBtnCont: 'carousel__button-container',
    carouselBtn: 'carousel__button',
    carouselBtnDis: 'carousel__button carousel__button--disabled',
    sectionHdrMain: 'section-container__header section-container__header--main',
    sectionHdr: 'section-container__header',
    sectionHdrPros: 'section-container__header section-container__header--pros',
    sectionHdrCons: 'section-container__header section-container__header--cons',
    sectionPar: 'section-container__paragraph',
    sectionParPros: 'section-container__paragraph section-container__paragraph--pros',
    sectionParCons: 'section-container__paragraph section-container__paragraph--cons',
    // db browser styles
    db: 'chili-db',
    dbHdr: 'chili-db__header',
    dbTitle: 'chili-db__title',
    dbMenu: 'chili-db__menu',
    dbMenuItem: 'chili-db__menu-item',
    dbMenuItemActive: 'chili-db__menu-item--active',
    dbMenuItemPhld: 'chili-db__menu-item--placeholder',
    dbBrowser: 'chili-db__browser',
    dbSearchCont: 'chili-db__list-search-container',
    dbFilterBtn: 'chili-db__list-filter',
    dbSearchField: 'chili-db__list-search-field',
    dbListCont: 'chili-db__list-container',
    dbListCol: 'chili-db__list-column',
    dbListItem: 'chili-db__list-item',
    dbListItemActive: 'chili-db__list-item--active',
    dbPrevCol: 'chili-db__preview-column',
    dbPrevTitle: 'chili-db__preview-title',
    dbPrevImgCont: 'chili-db__preview-img-container',
    dbPrevImg: 'chili-db__preview-img',
    dbPrvSpecs: 'chili-db__preview-specs',
    dbPrvSpecsItem: 'chili-db__preview-specs-item',
    dbPrvSpecsItemStrong: 'chili-db__preview-specs-item--strong',
    dbPrvDesc: 'chili-db__preview-description',
    hlText: 'chili-db__list-item--highlighted',
    // modal window styles
    modalWnd: 'modal-filter',
    modalWndVis: 'modal-filter modal-filter--visible',
    modalHdr: 'modal-filter__header',
    modalCloseBtn: 'modal-filter__close-button',
    modalColumnsCont: 'modal-filter__columns-container',
    modalColumn1: 'modal-filter__column modal-filter__column--spiciness',
    modalColumn2: 'modal-filter__column modal-filter__column--plant-size',
    modalColumn3: 'modal-filter__column modal-filter__column--fruit-size',
    modalColumn4: 'modal-filter__column modal-filter__column--fruit-shape',
    modalColumn5: 'modal-filter__column modal-filter__column--fruit-color',
    modalSubHdr: 'modal-filter__subheader',
    modalCheckboxEl: 'modal-filter__checkbox-element',
    modalCheckbox: 'modal-filter__checkbox',
    modalLbl: 'modal-filter__label',
    modalDropDn: 'modal-filter__dropdown',
    modalTag: 'modal-filter__tag',
    modalTagRemoveBtn: 'modal-filter__tag-remove-button',
    modalControlsCont: 'modal-filter__controls-container',
    modalControlBtn: 'modal-filter__control-button'
  },

  // OOCSS
  // temp placeholder
  {  // main section styles
    docTitle: 'documentTitle centered',
    section: 'sectionContainer bgGreyLight',
    carousel: 'carousel flexRow bgBlack',
    carouselBtnCont: 'buttonContainer flexRow',
    carouselBtn: 'buttonBorderless clWhite bgBlack hoverLime',
    carouselBtnDis: 'buttonBorderless disabled',
    sectionHdrMain: 'subheader sectionTitle clYellowPale centered',
    sectionHdr: 'subheader',
    sectionHdrPros: 'subheader clGreyLight bgGreen',
    sectionHdrCons: 'subheader clGreyLight bgRedDark',
    sectionPar: 'paragraph',
    sectionParPros: 'paragraph bgPros',
    sectionParCons: 'paragraph bgCons',
    // db browser styles
    db: 'chiliDb flexColumn bgConcrete borderDarkRounded',
    dbHdr: 'dbHeader',
    dbTitle: 'dbTitle centered',
    dbMenu: 'flexRow flexWrap',
    dbMenuItem: 'menuTab borderMT bgMT hoverYellowPale',
    dbMenuItemActive: 'hoverActive borderBottomOff bgGreyLight',
    dbMenuItemPhld: 'menuItemPlaceholder flexFill',
    dbBrowser: 'dbBrowser bgGreyLight',
    dbSearchCont: 'dbSearchContainer flexRow',
    dbFilterBtn: 'dbFilterButton hoverYellowPale',
    dbSearchField: 'dbSearchField',
    dbListCont: 'dbListContainer',
    dbListCol: 'dbListColumn',
    dbListItem: 'dbListItem clGreyDark',
    dbListItemActive: 'dbListItem clYellowPale bgGreyDark borderDottedYellow',
    dbPrevCol: 'dbPreviewColumn borderInsetRounded',
    dbPrevTitle: 'dbPreviewTitle centered',
    dbPrevImgCont: 'dbImageContainer',
    dbPrevImg: 'dbImage',
    dbPrvSpecs: 'dbPreviewSpecs',
    dbPrvSpecsItem: 'dbPreviewSpecsItem',
    dbPrvSpecsItemStrong: 'textStrong',
    dbPrvDesc: 'dbPreviewDescription',
    hlText: 'clPaper bgRedCoral',
    // modal window styles
    modalWnd: 'modalFilter bgWhite borderOutset',
    modalWndVis: 'modalFilter bgWhite borderOutset visible',
    modalHdr: 'modalFilterHeader centered',
    modalCloseBtn: 'closeButton hoverRed',
    modalColumnsCont: 'columnsContainer',
    modalColumn1: 'column flexColumn columnSpiciness',
    modalColumn2: 'column flexColumn columnPlantSize',
    modalColumn3: 'column flexColumn columnFruitSize',
    modalColumn4: 'column flexColumn columnFruitShape',
    modalColumn5: 'column flexColumn columnFruitColor',
    modalSubHdr: 'modalFilterSubheader',
    modalCheckboxEl: 'flexRow',
    modalCheckbox: 'checkbox',
    modalLbl: 'checkboxLabel',
    modalDropDn: 'dropdown',
    modalTag: 'tag clPaper bgGreenPale',
    modalTagRemoveBtn: 'tagRemoveButton',
    modalControlsCont: 'controlsContainer flexRow',
    modalControlBtn: 'controlButton hoverYellowPale'
  },

]