// classnames' templates
export const hlText = 'chili-db__list-item--highlighted';
export const modalWnd = condition => `modal-filter${condition ? ' modal-filter--visible' : ''}`;
export const modalHdr = 'modal-filter__header';
export const modalCloseBtn = 'modal-filter__close-button';
export const modalColumnsCntr = 'modal-filter__columns-container';
export const modalColumn = 'modal-filter__column';
export const modalSubHdr = 'modal-filter__subheader';
export const modalCheckboxEl = 'modal-filter__checkbox-element';
export const modalCheckbox = 'modal-filter__checkbox';
export const modalLbl = 'modal-filter__label';
export const modalDropDn = 'modal-filter__dropdown';
export const modalTag = 'modal-filter__tag';
export const modalTagRemoveBtn = 'modal-filter__tag-remove-button';
export const modalControlsCntr = 'modal-filter__controls-container';
export const modalControlBtn = 'modal-filter__control-button';

export const docTitle = 'document-title';
export const section = 'section-container';
export const carousel = 'carousel';
export const carouselBtnCnt = 'carousel__button-container';
export const carouselBtn = condition => `carousel__button${condition ? ' carousel__button--disabled' : ''}`;
export const sectionHdrMain = 'section-container__header section-container__header--main';
export const sectionHdr = 'section-container__header';
export const sectionHdrPros = 'section-container__header section-container__header--pros';
export const sectionHdrCons = 'section-container__header section-container__header--cons';
export const sectionPar = 'section-container__paragraph';
export const sectionParPros = 'section-container__paragraph section-container__paragraph--pros';
export const sectionParCons = 'section-container__paragraph section-container__paragraph--cons';

export const db = 'chili-db';
export const dbHdr = 'chili-db__header';
export const dbTitle = 'chili-db__title';
export const dbMenu = 'chili-db__menu';
export const dbMenuItem = 'chili-db__menu-item';
export const dbMenuItemActive = 'chili-db__menu-item--active';
export const dbMenuItemPhld = 'chili-db__menu-item--placeholder';
export const dbBrowser = 'chili-db__browser';
export const dbSearchCnt = 'chili-db__list-search-container';
export const dbFilterBtn = 'chili-db__list-filter';
export const dbSearchField = 'chili-db__list-search-field';
export const dbListCnt = 'chili-db__list-container';
export const dbListCol = 'chili-db__list-column';
export const dbListItem = 'chili-db__list-item';
export const dbListItemActive = 'chili-db__list-item--active';
export const dbPrvSpecs = 'chili-db__preview-specs';
export const dbPrvSpecsItem = 'chili-db__preview-specs-item';
export const dbPrvSpecsItemStrong = 'chili-db__preview-specs-item--strong';
export const dbPrvDesc = 'chili-db__preview-description';